### ISSUE TITLE
pydoc mocktest fails

### ISSUE THREAD

**Issue by jmgurney** [gfxmonk/mocktest#9]
Trying to get docs for mocktest w/ pydoc fails w/:
$pydoc mocktest
Traceback (most recent call last):
  File "/opt/local/bin/pydoc", line 5, in <module>
    pydoc.cli()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 2374, in cli
    help.help(arg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1839, in help
    elif request: doc(request, 'Help on %s:')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1578, in doc
    pager(render_doc(thing, title, forceload))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1573, in render_doc
    return title % desc + '\n\n' + text.document(object, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 361, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1153, in docmodule
    contents.append(self.docother(value, key, name, maxlen=70))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1359, in docother
    repr = self.repr(object)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/repr.py", line 24, in repr
    return self.repr1(x, self.maxlevel)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1008, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "./mocktest/matchers/base.py", line 48, in __repr__
    return self.desc()
  File "./mocktest/matchers/base.py", line 92, in matches
    raise RuntimeError("SplatMatcher instance used without prefixing with '*'")
RuntimeError: SplatMatcher instance used without prefixing with '*'

This is from eaa2fa877933b3de6b9cd8326143bf7231a59dfe.

**Comment by gfxmonk** [comment]
I've never used pydoc, so I have no idea what's going on here. The Makefile includes all the step for sphinx-build (might be a bit out of date, but it's a start).
